apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-depl
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:8.9.1
          env:
            - name: discovery.type
              value: 'single-node'
            - name: xpack.security.enabled
              value: 'false'
            - name: xpack.security.http.ssl.enabled
              value: 'false'
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-srv
spec:
  selector:
    app: elasticsearch
  ports:
    - name: elasticsearch-db
      protocol: TCP
      port: 9200
      targetPort: 9200
