apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: amansinghs/chatbot-server
          env:
            - name: ELASTIC_SEARCH_URI
              value: 'http://elasticsearch-srv:9200'
            - name: HF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: hf-api-key
                  key: HF_API_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: server-srv
spec:
  selector:
    app: server
  ports:
    - name: server
      protocol: TCP
      port: 3000
      targetPort: 3000
